#!/bin/bash

if [ $# != 1 ] ; then
echo -e "\n USAGE: $0 <ip_address|domain>\n"
exit 1;
fi
q=""
input=`echo $1|grep '[0-9]\{1,3\}[.][0-9]\{1,3\}[.][0-9]\{1,3\}[.][0-9]\{1,3\}'`
if [ -z "$input" ]
#if [ "$?" != "0" ]
then
	ip=`dig +short $1|tail -n 1`
	#ip=`echo $info|tail -n 1`
	if [ -z "$ip" ]
	then
		echo "Input illegal"
		exit 1;
	else
		dig +short $1
	       	echo  ""
		echo -e "IP: $ip\n"
		q=$ip
	fi
else
	q=$input
fi
org_str=`ipip_read $q|head -n 1`
asb=`curl  -s http://check.my/$q  |sed -E 's/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}//g'`
#curl -A "ipip/tt" --compressed  -m 1 http://btapi.ipip.net/host/info?ip=$1&host=

echo -e $org_str$asb
