#!/bin/bash

#$1 = filename prefix. Format is ss_$1.json.It's also password
#$2 = port . a numble of listening
#$3 = method. Encrypted Method
if [ $# != 3 ] ; then
echo -e "\n USAGE: $0 filename_prefix port method\n"
exit 1;
fi

file=ss_$1.json
if [ -f $file ];
then
    rm $file
fi
port=$2
mtd=$3
pswd=$1

eval echo -e  `cat /etc/ss_tpl.tpl` >>$file
log_port $2