#!/bin/bash
#sudo killall ss-server
if test -z "$1"
then 
	sslist_path=`pwd`
else
	sslist_path=$1
fi
dm_prefix=${sslist_path##*/}
lst_ip=`dig $dm_prefix'.gzlong7.net' +short @8.8.8.8|tail -n 1`
if test -z "$lst_ip"
then
	ex_para=""
else
	ex_para="-s "$lst_ip
fi
for file in `ls $sslist_path/*.json`
do
	#  	cat $file
    port=`cat $file|grep "server_port"|grep -Eo "[0-9]+"`
    if [ "$port" -gt 1024 ]
    then runss $file $ex_para
    else sudo runss $file $ex_para
    fi
    log_port $port
#   ss-server -u -c $file  >/dev/null 2>&1 &
done
