#!/bin/bash
#sudo killall ss-server
if test -z "$1"
then 
	sslist_path=`pwd`
else
	sslist_path=$1
fi
for file in `ls $sslist_path/*.json`
do
	#  	cat $file
    port=`cat $file|grep "server_port"|grep -Eo "[0-9]+"`
    if [ "$port" -gt 1024 ]
    then runss $file
    else sudo runss $file
    fi
    log_port $port
#   ss-server -u -c $file  >/dev/null 2>&1 &
done
