#!/bin/bash

file=$1
filebak=$file"_bak"
port=`cat $file|grep "server_port"|grep -Eo "[0-9]+"`
password=`cat $file|grep "password"|regex ":\"(.*?)\"",`
method=`cat $file|grep "method"|regex ":\"(.*?)\"",`
mv $file $filebak
jsonwrite $password $port $method

